// This file is auto-generated from pi-ai models.generated.js
// Do not edit manually.

import type { KnownProvider } from "@mariozechner/pi-ai";

import type { ProviderModelInfo } from "./types.js";

type ProviderModelRegistry = { [K in KnownProvider]: ProviderModelInfo[] };

export const PROVIDER_MODELS = {
  "amazon-bedrock": [
    {"id":"eu.anthropic.claude-opus-4-5-20251101-v1:0","name":"Claude Opus 4.5 (EU)","size":"large"},
    {"id":"global.anthropic.claude-opus-4-5-20251101-v1:0","name":"Claude Opus 4.5","size":"large"},
    {"id":"eu.anthropic.claude-haiku-4-5-20251001-v1:0","name":"Claude Haiku 4.5 (EU)","size":"normal"},
    {"id":"global.anthropic.claude-haiku-4-5-20251001-v1:0","name":"Claude Haiku 4.5","size":"normal"},
    {"id":"eu.anthropic.claude-sonnet-4-5-20250929-v1:0","name":"Claude Sonnet 4.5 (EU)","size":"normal"},
    {"id":"global.anthropic.claude-sonnet-4-5-20250929-v1:0","name":"Claude Sonnet 4.5","size":"normal"},
    {"id":"us.anthropic.claude-opus-4-1-20250805-v1:0","name":"Claude Opus 4.1","size":"large"},
    {"id":"us.anthropic.claude-opus-4-20250514-v1:0","name":"Claude Opus 4","size":"large"},
    {"id":"global.anthropic.claude-sonnet-4-20250514-v1:0","name":"Claude Sonnet 4","size":"normal"},
    {"id":"us.anthropic.claude-3-7-sonnet-20250219-v1:0","name":"Claude Sonnet 3.7","size":"normal"},
    {"id":"anthropic.claude-3-5-haiku-20241022-v1:0","name":"Claude Haiku 3.5","size":"normal"},
    {"id":"anthropic.claude-3-5-sonnet-20241022-v2:0","name":"Claude Sonnet 3.5 v2","size":"normal"},
    {"id":"anthropic.claude-3-5-sonnet-20240620-v1:0","name":"Claude Sonnet 3.5","size":"normal"},
    {"id":"anthropic.claude-3-haiku-20240307-v1:0","name":"Claude Haiku 3","size":"normal"},
    {"id":"anthropic.claude-3-opus-20240229-v1:0","name":"Claude Opus 3","size":"large"},
    {"id":"anthropic.claude-3-sonnet-20240229-v1:0","name":"Claude Sonnet 3","size":"normal"},
    {"id":"us.amazon.nova-premier-v1:0","name":"Nova Premier","size":"normal"},
    {"id":"moonshot.kimi-k2-thinking","name":"Kimi K2 Thinking","size":"normal"},
    {"id":"minimax.minimax-m2","name":"MiniMax M2","size":"normal"},
    {"id":"deepseek.v3-v1:0","name":"DeepSeek-V3.1","size":"normal"},
    {"id":"us.deepseek.r1-v1:0","name":"DeepSeek-R1","size":"normal"},
    {"id":"qwen.qwen3-32b-v1:0","name":"Qwen3 32B (dense)","size":"normal"},
    {"id":"us.amazon.nova-pro-v1:0","name":"Nova Pro","size":"normal"},
    {"id":"cohere.command-r-plus-v1:0","name":"Command R+","size":"normal"},
    {"id":"us.meta.llama4-scout-17b-instruct-v1:0","name":"Llama 4 Scout 17B Instruct","size":"normal"},
    {"id":"us.meta.llama4-maverick-17b-instruct-v1:0","name":"Llama 4 Maverick 17B Instruct","size":"normal"},
    {"id":"qwen.qwen3-235b-a22b-2507-v1:0","name":"Qwen3 235B A22B 2507","size":"normal"},
    {"id":"qwen.qwen3-coder-30b-a3b-v1:0","name":"Qwen3 Coder 30B A3B Instruct","size":"normal"},
    {"id":"qwen.qwen3-next-80b-a3b","name":"Qwen/Qwen3-Next-80B-A3B-Instruct","size":"normal"},
    {"id":"qwen.qwen3-vl-235b-a22b","name":"Qwen/Qwen3-VL-235B-A22B-Instruct","size":"normal"},
    {"id":"google.gemma-3-27b-it","name":"Google Gemma 3 27B Instruct","size":"normal"},
    {"id":"qwen.qwen3-coder-480b-a35b-v1:0","name":"Qwen3 Coder 480B A35B Instruct","size":"normal"},
    {"id":"us.meta.llama3-2-1b-instruct-v1:0","name":"Llama 3.2 1B Instruct","size":"normal"},
    {"id":"us.meta.llama3-2-3b-instruct-v1:0","name":"Llama 3.2 3B Instruct","size":"normal"},
    {"id":"us.amazon.nova-micro-v1:0","name":"Nova Micro","size":"normal"},
    {"id":"cohere.command-r-v1:0","name":"Command R","size":"normal"},
    {"id":"google.gemma-3-4b-it","name":"Gemma 3 4B IT","size":"normal"},
    {"id":"meta.llama3-1-70b-instruct-v1:0","name":"Llama 3.1 70B Instruct","size":"normal"},
    {"id":"meta.llama3-1-8b-instruct-v1:0","name":"Llama 3.1 8B Instruct","size":"normal"},
    {"id":"mistral.mistral-large-2402-v1:0","name":"Mistral Large (24.02)","size":"normal"},
    {"id":"openai.gpt-oss-120b-1:0","name":"gpt-oss-120b","size":"normal"},
    {"id":"openai.gpt-oss-20b-1:0","name":"gpt-oss-20b","size":"normal"},
    {"id":"openai.gpt-oss-safeguard-120b","name":"GPT OSS Safeguard 120B","size":"normal"},
    {"id":"openai.gpt-oss-safeguard-20b","name":"GPT OSS Safeguard 20B","size":"normal"},
    {"id":"us.meta.llama3-2-11b-instruct-v1:0","name":"Llama 3.2 11B Instruct","size":"normal"},
    {"id":"us.meta.llama3-2-90b-instruct-v1:0","name":"Llama 3.2 90B Instruct","size":"normal"},
    {"id":"us.meta.llama3-3-70b-instruct-v1:0","name":"Llama 3.3 70B Instruct","size":"normal"},
    {"id":"us.amazon.nova-lite-v1:0","name":"Nova Lite","size":"normal"},
    {"id":"global.amazon.nova-2-lite-v1:0","name":"Nova 2 Lite","size":"normal"},
    {"id":"mistral.ministral-3-14b-instruct","name":"Ministral 14B 3.0","size":"normal"},
    {"id":"mistral.ministral-3-8b-instruct","name":"Ministral 3 8B","size":"normal"},
    {"id":"mistral.voxtral-mini-3b-2507","name":"Voxtral Mini 3B 2507","size":"normal"},
    {"id":"nvidia.nemotron-nano-12b-v2","name":"NVIDIA Nemotron Nano 12B v2 VL BF16","size":"normal"},
    {"id":"nvidia.nemotron-nano-9b-v2","name":"NVIDIA Nemotron Nano 9B v2","size":"normal"},
    {"id":"mistral.voxtral-small-24b-2507","name":"Voxtral Small 24B 2507","size":"normal"},
  ],
  "anthropic": [
    {"id":"claude-opus-4-5","name":"Claude Opus 4.5 (latest)","size":"large"},
    {"id":"claude-opus-4-0","name":"Claude Opus 4 (latest)","size":"large"},
    {"id":"claude-opus-4-1","name":"Claude Opus 4.1 (latest)","size":"large"},
    {"id":"claude-3-7-sonnet-latest","name":"Claude Sonnet 3.7 (latest)","size":"normal"},
    {"id":"claude-haiku-4-5","name":"Claude Haiku 4.5 (latest)","size":"normal"},
    {"id":"claude-sonnet-4-0","name":"Claude Sonnet 4 (latest)","size":"normal"},
    {"id":"claude-sonnet-4-5","name":"Claude Sonnet 4.5 (latest)","size":"normal"},
    {"id":"claude-3-5-haiku-latest","name":"Claude Haiku 3.5 (latest)","size":"normal"},
    {"id":"claude-opus-4-5-20251101","name":"Claude Opus 4.5","size":"large"},
    {"id":"claude-haiku-4-5-20251001","name":"Claude Haiku 4.5","size":"normal"},
    {"id":"claude-sonnet-4-5-20250929","name":"Claude Sonnet 4.5","size":"normal"},
    {"id":"claude-opus-4-1-20250805","name":"Claude Opus 4.1","size":"large"},
    {"id":"claude-opus-4-20250514","name":"Claude Opus 4","size":"large"},
    {"id":"claude-sonnet-4-20250514","name":"Claude Sonnet 4","size":"normal"},
    {"id":"claude-3-7-sonnet-20250219","name":"Claude Sonnet 3.7","size":"normal"},
    {"id":"claude-3-5-haiku-20241022","name":"Claude Haiku 3.5","size":"normal"},
    {"id":"claude-3-5-sonnet-20241022","name":"Claude Sonnet 3.5 v2","size":"normal"},
    {"id":"claude-3-5-sonnet-20240620","name":"Claude Sonnet 3.5","size":"normal"},
    {"id":"claude-3-haiku-20240307","name":"Claude Haiku 3","size":"normal"},
    {"id":"claude-3-opus-20240229","name":"Claude Opus 3","size":"large"},
    {"id":"claude-3-sonnet-20240229","name":"Claude Sonnet 3","size":"normal"},
  ],
  "azure-openai-responses": [
    {"id":"gpt-5.1-chat-latest","name":"GPT-5.1 Chat","size":"normal"},
    {"id":"gpt-5.2-chat-latest","name":"GPT-5.2 Chat","size":"normal"},
    {"id":"codex-mini-latest","name":"Codex Mini","size":"normal"},
    {"id":"gpt-5-chat-latest","name":"GPT-5 Chat Latest","size":"normal"},
    {"id":"gpt-4o-2024-11-20","name":"GPT-4o (2024-11-20)","size":"normal"},
    {"id":"gpt-4o-2024-08-06","name":"GPT-4o (2024-08-06)","size":"normal"},
    {"id":"gpt-4o-2024-05-13","name":"GPT-4o (2024-05-13)","size":"normal"},
    {"id":"gpt-5-pro","name":"GPT-5 Pro","size":"normal"},
    {"id":"gpt-5.1-codex-max","name":"GPT-5.1 Codex Max","size":"normal"},
    {"id":"gpt-5.2-pro","name":"GPT-5.2 Pro","size":"normal"},
    {"id":"o1-pro","name":"o1-pro","size":"normal"},
    {"id":"o3-pro","name":"o3-pro","size":"normal"},
    {"id":"gpt-5","name":"GPT-5","size":"normal"},
    {"id":"gpt-5-codex","name":"GPT-5-Codex","size":"normal"},
    {"id":"gpt-5.1","name":"GPT-5.1","size":"normal"},
    {"id":"gpt-5.1-codex","name":"GPT-5.1 Codex","size":"normal"},
    {"id":"gpt-5.2","name":"GPT-5.2","size":"normal"},
    {"id":"gpt-5.2-codex","name":"GPT-5.2 Codex","size":"normal"},
    {"id":"o1","name":"o1","size":"normal"},
    {"id":"o3","name":"o3","size":"normal"},
    {"id":"o3-deep-research","name":"o3-deep-research","size":"normal"},
    {"id":"gpt-5-mini","name":"GPT-5 Mini","size":"normal"},
    {"id":"gpt-5-nano","name":"GPT-5 Nano","size":"normal"},
    {"id":"gpt-5.1-codex-mini","name":"GPT-5.1 Codex mini","size":"normal"},
    {"id":"o3-mini","name":"o3-mini","size":"normal"},
    {"id":"o4-mini","name":"o4-mini","size":"normal"},
    {"id":"o4-mini-deep-research","name":"o4-mini-deep-research","size":"normal"},
    {"id":"gpt-4.1","name":"GPT-4.1","size":"normal"},
    {"id":"gpt-4o","name":"GPT-4o","size":"normal"},
    {"id":"gpt-4-turbo","name":"GPT-4 Turbo","size":"normal"},
    {"id":"gpt-4","name":"GPT-4","size":"normal"},
    {"id":"gpt-4.1-mini","name":"GPT-4.1 mini","size":"normal"},
    {"id":"gpt-4.1-nano","name":"GPT-4.1 nano","size":"normal"},
    {"id":"gpt-4o-mini","name":"GPT-4o mini","size":"normal"},
  ],
  "cerebras": [
    {"id":"gpt-oss-120b","name":"GPT OSS 120B","size":"normal"},
    {"id":"zai-glm-4.7","name":"Z.AI GLM-4.7","size":"normal"},
    {"id":"qwen-3-235b-a22b-instruct-2507","name":"Qwen 3 235B Instruct","size":"normal"},
  ],
  "github-copilot": [
    {"id":"gpt-5.1-codex-max","name":"GPT-5.1-Codex-max","size":"normal"},
    {"id":"claude-opus-4.5","name":"Claude Opus 4.5","size":"large"},
    {"id":"gpt-5.2-codex","name":"GPT-5.2-Codex","size":"normal"},
    {"id":"gpt-5","name":"GPT-5","size":"normal"},
    {"id":"gpt-5.1","name":"GPT-5.1","size":"normal"},
    {"id":"gpt-5.1-codex","name":"GPT-5.1-Codex","size":"normal"},
    {"id":"gemini-3-pro-preview","name":"Gemini 3 Pro Preview","size":"normal"},
    {"id":"gpt-5.2","name":"GPT-5.2","size":"normal"},
    {"id":"grok-code-fast-1","name":"Grok Code Fast 1","size":"normal"},
    {"id":"claude-haiku-4.5","name":"Claude Haiku 4.5","size":"normal"},
    {"id":"claude-sonnet-4","name":"Claude Sonnet 4","size":"normal"},
    {"id":"claude-sonnet-4.5","name":"Claude Sonnet 4.5","size":"normal"},
    {"id":"gpt-5.1-codex-mini","name":"GPT-5.1-Codex-mini","size":"normal"},
    {"id":"gemini-3-flash-preview","name":"Gemini 3 Flash","size":"small"},
    {"id":"gpt-5-mini","name":"GPT-5-mini","size":"normal"},
    {"id":"gemini-2.5-pro","name":"Gemini 2.5 Pro","size":"normal"},
    {"id":"gpt-4.1","name":"GPT-4.1","size":"normal"},
    {"id":"gpt-4o","name":"GPT-4o","size":"normal"},
  ],
  "google": [
    {"id":"gemini-flash-latest","name":"Gemini Flash Latest","size":"small"},
    {"id":"gemini-flash-lite-latest","name":"Gemini Flash-Lite Latest","size":"small"},
    {"id":"gemini-2.5-pro","name":"Gemini 2.5 Pro","size":"normal"},
    {"id":"gemini-2.5-pro-preview-05-06","name":"Gemini 2.5 Pro Preview 05-06","size":"normal"},
    {"id":"gemini-2.5-pro-preview-06-05","name":"Gemini 2.5 Pro Preview 06-05","size":"normal"},
    {"id":"gemini-3-pro-preview","name":"Gemini 3 Pro Preview","size":"normal"},
    {"id":"gemini-2.5-flash","name":"Gemini 2.5 Flash","size":"small"},
    {"id":"gemini-2.5-flash-lite","name":"Gemini 2.5 Flash Lite","size":"small"},
    {"id":"gemini-2.5-flash-lite-preview-06-17","name":"Gemini 2.5 Flash Lite Preview 06-17","size":"small"},
    {"id":"gemini-2.5-flash-lite-preview-09-2025","name":"Gemini 2.5 Flash Lite Preview 09-25","size":"small"},
    {"id":"gemini-2.5-flash-preview-04-17","name":"Gemini 2.5 Flash Preview 04-17","size":"small"},
    {"id":"gemini-2.5-flash-preview-05-20","name":"Gemini 2.5 Flash Preview 05-20","size":"small"},
    {"id":"gemini-2.5-flash-preview-09-2025","name":"Gemini 2.5 Flash Preview 09-25","size":"small"},
    {"id":"gemini-3-flash-preview","name":"Gemini 3 Flash Preview","size":"small"},
    {"id":"gemini-live-2.5-flash-preview-native-audio","name":"Gemini Live 2.5 Flash Preview Native Audio","size":"small"},
    {"id":"gemini-live-2.5-flash","name":"Gemini Live 2.5 Flash","size":"small"},
    {"id":"gemini-1.5-pro","name":"Gemini 1.5 Pro","size":"normal"},
    {"id":"gemini-2.0-flash","name":"Gemini 2.0 Flash","size":"small"},
    {"id":"gemini-2.0-flash-lite","name":"Gemini 2.0 Flash Lite","size":"small"},
    {"id":"gemini-1.5-flash","name":"Gemini 1.5 Flash","size":"small"},
    {"id":"gemini-1.5-flash-8b","name":"Gemini 1.5 Flash-8B","size":"small"},
  ],
  "google-antigravity": [
    {"id":"claude-opus-4-5-thinking","name":"Claude Opus 4.5 Thinking (Antigravity)","size":"large"},
    {"id":"gemini-3-pro-high","name":"Gemini 3 Pro High (Antigravity)","size":"normal"},
    {"id":"gemini-3-pro-low","name":"Gemini 3 Pro Low (Antigravity)","size":"normal"},
    {"id":"claude-sonnet-4-5-thinking","name":"Claude Sonnet 4.5 Thinking (Antigravity)","size":"normal"},
    {"id":"gemini-3-flash","name":"Gemini 3 Flash (Antigravity)","size":"small"},
    {"id":"gpt-oss-120b-medium","name":"GPT-OSS 120B Medium (Antigravity)","size":"normal"},
    {"id":"claude-sonnet-4-5","name":"Claude Sonnet 4.5 (Antigravity)","size":"normal"},
  ],
  "google-gemini-cli": [
    {"id":"gemini-2.5-pro","name":"Gemini 2.5 Pro (Cloud Code Assist)","size":"normal"},
    {"id":"gemini-3-pro-preview","name":"Gemini 3 Pro Preview (Cloud Code Assist)","size":"normal"},
    {"id":"gemini-2.5-flash","name":"Gemini 2.5 Flash (Cloud Code Assist)","size":"small"},
    {"id":"gemini-3-flash-preview","name":"Gemini 3 Flash Preview (Cloud Code Assist)","size":"small"},
    {"id":"gemini-2.0-flash","name":"Gemini 2.0 Flash (Cloud Code Assist)","size":"small"},
  ],
  "google-vertex": [
    {"id":"gemini-2.5-pro","name":"Gemini 2.5 Pro (Vertex)","size":"normal"},
    {"id":"gemini-3-pro-preview","name":"Gemini 3 Pro Preview (Vertex)","size":"normal"},
    {"id":"gemini-2.0-flash-lite","name":"Gemini 2.0 Flash Lite (Vertex)","size":"small"},
    {"id":"gemini-2.5-flash","name":"Gemini 2.5 Flash (Vertex)","size":"small"},
    {"id":"gemini-2.5-flash-lite","name":"Gemini 2.5 Flash Lite (Vertex)","size":"small"},
    {"id":"gemini-2.5-flash-lite-preview-09-2025","name":"Gemini 2.5 Flash Lite Preview 09-25 (Vertex)","size":"small"},
    {"id":"gemini-3-flash-preview","name":"Gemini 3 Flash Preview (Vertex)","size":"small"},
    {"id":"gemini-1.5-pro","name":"Gemini 1.5 Pro (Vertex)","size":"normal"},
    {"id":"gemini-2.0-flash","name":"Gemini 2.0 Flash (Vertex)","size":"small"},
    {"id":"gemini-1.5-flash","name":"Gemini 1.5 Flash (Vertex)","size":"small"},
    {"id":"gemini-1.5-flash-8b","name":"Gemini 1.5 Flash-8B (Vertex)","size":"small"},
  ],
  "groq": [
    {"id":"openai/gpt-oss-120b","name":"GPT OSS 120B","size":"normal"},
    {"id":"openai/gpt-oss-20b","name":"GPT OSS 20B","size":"normal"},
    {"id":"qwen-qwq-32b","name":"Qwen QwQ 32B","size":"normal"},
    {"id":"qwen/qwen3-32b","name":"Qwen3 32B","size":"normal"},
    {"id":"deepseek-r1-distill-llama-70b","name":"DeepSeek R1 Distill Llama 70B","size":"normal"},
    {"id":"moonshotai/kimi-k2-instruct-0905","name":"Kimi K2 Instruct 0905","size":"normal"},
    {"id":"llama-3.1-8b-instant","name":"Llama 3.1 8B Instant","size":"normal"},
    {"id":"llama-3.3-70b-versatile","name":"Llama 3.3 70B Versatile","size":"normal"},
    {"id":"moonshotai/kimi-k2-instruct","name":"Kimi K2 Instruct","size":"normal"},
    {"id":"meta-llama/llama-4-maverick-17b-128e-instruct","name":"Llama 4 Maverick 17B","size":"normal"},
    {"id":"meta-llama/llama-4-scout-17b-16e-instruct","name":"Llama 4 Scout 17B","size":"normal"},
    {"id":"mistral-saba-24b","name":"Mistral Saba 24B","size":"normal"},
    {"id":"gemma2-9b-it","name":"Gemma 2 9B","size":"normal"},
    {"id":"llama3-70b-8192","name":"Llama 3 70B","size":"normal"},
    {"id":"llama3-8b-8192","name":"Llama 3 8B","size":"normal"},
  ],
  "huggingface": [
    {"id":"moonshotai/Kimi-K2-Thinking","name":"Kimi-K2-Thinking","size":"normal"},
    {"id":"moonshotai/Kimi-K2.5","name":"Kimi-K2.5","size":"normal"},
    {"id":"Qwen/Qwen3-235B-A22B-Thinking-2507","name":"Qwen3-235B-A22B-Thinking-2507","size":"normal"},
    {"id":"XiaomiMiMo/MiMo-V2-Flash","name":"MiMo-V2-Flash","size":"normal"},
    {"id":"MiniMaxAI/MiniMax-M2.1","name":"MiniMax-M2.1","size":"normal"},
    {"id":"zai-org/GLM-4.7","name":"GLM-4.7","size":"normal"},
    {"id":"zai-org/GLM-4.7-Flash","name":"GLM-4.7-Flash","size":"normal"},
    {"id":"deepseek-ai/DeepSeek-R1-0528","name":"DeepSeek-R1-0528","size":"normal"},
    {"id":"deepseek-ai/DeepSeek-V3.2","name":"DeepSeek-V3.2","size":"normal"},
    {"id":"Qwen/Qwen3-Next-80B-A3B-Thinking","name":"Qwen3-Next-80B-A3B-Thinking","size":"normal"},
    {"id":"Qwen/Qwen3-Coder-480B-A35B-Instruct","name":"Qwen3-Coder-480B-A35B-Instruct","size":"normal"},
    {"id":"Qwen/Qwen3-Next-80B-A3B-Instruct","name":"Qwen3-Next-80B-A3B-Instruct","size":"normal"},
    {"id":"moonshotai/Kimi-K2-Instruct-0905","name":"Kimi-K2-Instruct-0905","size":"normal"},
    {"id":"moonshotai/Kimi-K2-Instruct","name":"Kimi-K2-Instruct","size":"normal"},
  ],
  "kimi-coding": [
    {"id":"k2p5","name":"Kimi K2.5","size":"normal"},
    {"id":"kimi-k2-thinking","name":"Kimi K2 Thinking","size":"normal"},
  ],
  "minimax": [
    {"id":"MiniMax-M2.1","name":"MiniMax-M2.1","size":"normal"},
    {"id":"MiniMax-M2","name":"MiniMax-M2","size":"normal"},
  ],
  "minimax-cn": [
    {"id":"MiniMax-M2.1","name":"MiniMax-M2.1","size":"normal"},
    {"id":"MiniMax-M2","name":"MiniMax-M2","size":"normal"},
  ],
  "mistral": [
    {"id":"magistral-medium-latest","name":"Magistral Medium","size":"normal"},
    {"id":"devstral-medium-latest","name":"Devstral 2","size":"normal"},
    {"id":"mistral-medium-latest","name":"Mistral Medium","size":"normal"},
    {"id":"mistral-large-latest","name":"Mistral Large","size":"normal"},
    {"id":"codestral-latest","name":"Codestral","size":"normal"},
    {"id":"pixtral-large-latest","name":"Pixtral Large","size":"normal"},
    {"id":"ministral-3b-latest","name":"Ministral 3B","size":"normal"},
    {"id":"ministral-8b-latest","name":"Ministral 8B","size":"normal"},
    {"id":"mistral-small-latest","name":"Mistral Small","size":"normal"},
    {"id":"magistral-small","name":"Magistral Small","size":"normal"},
    {"id":"mistral-medium-2508","name":"Mistral Medium 3.1","size":"normal"},
    {"id":"mistral-medium-2505","name":"Mistral Medium 3","size":"normal"},
    {"id":"devstral-medium-2507","name":"Devstral Medium","size":"normal"},
    {"id":"devstral-2512","name":"Devstral 2","size":"normal"},
    {"id":"mistral-large-2512","name":"Mistral Large 3","size":"normal"},
    {"id":"mistral-large-2411","name":"Mistral Large 2.1","size":"normal"},
    {"id":"mistral-nemo","name":"Mistral Nemo","size":"normal"},
    {"id":"pixtral-12b","name":"Pixtral 12B","size":"normal"},
    {"id":"open-mixtral-8x22b","name":"Mixtral 8x22B","size":"normal"},
    {"id":"open-mixtral-8x7b","name":"Mixtral 8x7B","size":"normal"},
    {"id":"open-mistral-7b","name":"Mistral 7B","size":"normal"},
    {"id":"labs-devstral-small-2512","name":"Devstral Small 2","size":"normal"},
    {"id":"devstral-small-2505","name":"Devstral Small 2505","size":"normal"},
    {"id":"devstral-small-2507","name":"Devstral Small","size":"normal"},
    {"id":"mistral-small-2506","name":"Mistral Small 3.2","size":"normal"},
  ],
  "openai": [
    {"id":"gpt-5.1-chat-latest","name":"GPT-5.1 Chat","size":"normal"},
    {"id":"gpt-5.2-chat-latest","name":"GPT-5.2 Chat","size":"normal"},
    {"id":"codex-mini-latest","name":"Codex Mini","size":"normal"},
    {"id":"gpt-5-chat-latest","name":"GPT-5 Chat Latest","size":"normal"},
    {"id":"gpt-4o-2024-11-20","name":"GPT-4o (2024-11-20)","size":"normal"},
    {"id":"gpt-4o-2024-08-06","name":"GPT-4o (2024-08-06)","size":"normal"},
    {"id":"gpt-4o-2024-05-13","name":"GPT-4o (2024-05-13)","size":"normal"},
    {"id":"gpt-5-pro","name":"GPT-5 Pro","size":"normal"},
    {"id":"gpt-5.1-codex-max","name":"GPT-5.1 Codex Max","size":"normal"},
    {"id":"gpt-5.2-pro","name":"GPT-5.2 Pro","size":"normal"},
    {"id":"o1-pro","name":"o1-pro","size":"normal"},
    {"id":"o3-pro","name":"o3-pro","size":"normal"},
    {"id":"gpt-5","name":"GPT-5","size":"normal"},
    {"id":"gpt-5-codex","name":"GPT-5-Codex","size":"normal"},
    {"id":"gpt-5.1","name":"GPT-5.1","size":"normal"},
    {"id":"gpt-5.1-codex","name":"GPT-5.1 Codex","size":"normal"},
    {"id":"gpt-5.2","name":"GPT-5.2","size":"normal"},
    {"id":"gpt-5.2-codex","name":"GPT-5.2 Codex","size":"normal"},
    {"id":"o1","name":"o1","size":"normal"},
    {"id":"o3","name":"o3","size":"normal"},
    {"id":"o3-deep-research","name":"o3-deep-research","size":"normal"},
    {"id":"gpt-5-mini","name":"GPT-5 Mini","size":"normal"},
    {"id":"gpt-5-nano","name":"GPT-5 Nano","size":"normal"},
    {"id":"gpt-5.1-codex-mini","name":"GPT-5.1 Codex mini","size":"normal"},
    {"id":"o3-mini","name":"o3-mini","size":"normal"},
    {"id":"o4-mini","name":"o4-mini","size":"normal"},
    {"id":"o4-mini-deep-research","name":"o4-mini-deep-research","size":"normal"},
    {"id":"gpt-4.1","name":"GPT-4.1","size":"normal"},
    {"id":"gpt-4o","name":"GPT-4o","size":"normal"},
    {"id":"gpt-4-turbo","name":"GPT-4 Turbo","size":"normal"},
    {"id":"gpt-4","name":"GPT-4","size":"normal"},
    {"id":"gpt-4.1-mini","name":"GPT-4.1 mini","size":"normal"},
    {"id":"gpt-4.1-nano","name":"GPT-4.1 nano","size":"normal"},
    {"id":"gpt-4o-mini","name":"GPT-4o mini","size":"normal"},
  ],
  "openai-codex": [
    {"id":"gpt-5.1-codex-max","name":"GPT-5.1 Codex Max","size":"normal"},
    {"id":"gpt-5.1","name":"GPT-5.1","size":"normal"},
    {"id":"gpt-5.2","name":"GPT-5.2","size":"normal"},
    {"id":"gpt-5.2-codex","name":"GPT-5.2 Codex","size":"normal"},
    {"id":"gpt-5.1-codex-mini","name":"GPT-5.1 Codex Mini","size":"normal"},
  ],
  "opencode": [
    {"id":"gpt-5.1-codex-max","name":"GPT-5.1 Codex Max","size":"normal"},
    {"id":"claude-opus-4-5","name":"Claude Opus 4.5","size":"large"},
    {"id":"claude-opus-4-1","name":"Claude Opus 4.1","size":"large"},
    {"id":"gemini-3-pro","name":"Gemini 3 Pro","size":"normal"},
    {"id":"claude-sonnet-4","name":"Claude Sonnet 4","size":"normal"},
    {"id":"claude-sonnet-4-5","name":"Claude Sonnet 4.5","size":"normal"},
    {"id":"gpt-5","name":"GPT-5","size":"normal"},
    {"id":"gpt-5-codex","name":"GPT-5 Codex","size":"normal"},
    {"id":"gpt-5.1","name":"GPT-5.1","size":"normal"},
    {"id":"gpt-5.1-codex","name":"GPT-5.1 Codex","size":"normal"},
    {"id":"gpt-5.2","name":"GPT-5.2","size":"normal"},
    {"id":"gpt-5.2-codex","name":"GPT-5.2 Codex","size":"normal"},
    {"id":"kimi-k2-thinking","name":"Kimi K2 Thinking","size":"normal"},
    {"id":"kimi-k2.5","name":"Kimi K2.5","size":"normal"},
    {"id":"glm-4.6","name":"GLM-4.6","size":"normal"},
    {"id":"glm-4.7","name":"GLM-4.7","size":"normal"},
    {"id":"minimax-m2.1","name":"MiniMax M2.1","size":"normal"},
    {"id":"big-pickle","name":"Big Pickle","size":"normal"},
    {"id":"claude-haiku-4-5","name":"Claude Haiku 4.5","size":"normal"},
    {"id":"gemini-3-flash","name":"Gemini 3 Flash","size":"small"},
    {"id":"gpt-5-nano","name":"GPT-5 Nano","size":"normal"},
    {"id":"gpt-5.1-codex-mini","name":"GPT-5.1 Codex Mini","size":"normal"},
    {"id":"kimi-k2","name":"Kimi K2","size":"normal"},
    {"id":"qwen3-coder","name":"Qwen3 Coder","size":"normal"},
    {"id":"claude-3-5-haiku","name":"Claude Haiku 3.5","size":"normal"},
  ],
  "openrouter": [
    {"id":"qwen/qwen-plus-2025-07-28:thinking","name":"Qwen: Qwen Plus 0728 (thinking)","size":"normal"},
    {"id":"qwen/qwen-plus-2025-07-28","name":"Qwen: Qwen Plus 0728","size":"normal"},
    {"id":"openai/gpt-4o-2024-11-20","name":"OpenAI: GPT-4o (2024-11-20)","size":"normal"},
    {"id":"openai/gpt-4o-2024-08-06","name":"OpenAI: GPT-4o (2024-08-06)","size":"normal"},
    {"id":"openai/gpt-4o-mini-2024-07-18","name":"OpenAI: GPT-4o-mini (2024-07-18)","size":"normal"},
    {"id":"openai/gpt-4o-2024-05-13","name":"OpenAI: GPT-4o (2024-05-13)","size":"normal"},
    {"id":"openai/gpt-5-pro","name":"OpenAI: GPT-5 Pro","size":"normal"},
    {"id":"openai/gpt-5.1-codex-max","name":"OpenAI: GPT-5.1-Codex-Max","size":"normal"},
    {"id":"openai/gpt-5.2-pro","name":"OpenAI: GPT-5.2 Pro","size":"normal"},
    {"id":"openai/o3-pro","name":"OpenAI: o3 Pro","size":"normal"},
    {"id":"anthropic/claude-opus-4.5","name":"Anthropic: Claude Opus 4.5","size":"large"},
    {"id":"anthropic/claude-opus-4","name":"Anthropic: Claude Opus 4","size":"large"},
    {"id":"anthropic/claude-opus-4.1","name":"Anthropic: Claude Opus 4.1","size":"large"},
    {"id":"upstage/solar-pro-3:free","name":"Upstage: Solar Pro 3 (free)","size":"normal"},
    {"id":"openrouter/auto","name":"OpenRouter: Auto Router","size":"normal"},
    {"id":"x-ai/grok-4-fast","name":"xAI: Grok 4 Fast","size":"normal"},
    {"id":"x-ai/grok-4.1-fast","name":"xAI: Grok 4.1 Fast","size":"normal"},
    {"id":"google/gemini-2.5-pro","name":"Google: Gemini 2.5 Pro","size":"normal"},
    {"id":"google/gemini-2.5-pro-preview","name":"Google: Gemini 2.5 Pro Preview 06-05","size":"normal"},
    {"id":"google/gemini-3-pro-preview","name":"Google: Gemini 3 Pro Preview","size":"normal"},
    {"id":"google/gemini-2.5-pro-preview-05-06","name":"Google: Gemini 2.5 Pro Preview 05-06","size":"normal"},
    {"id":"anthropic/claude-sonnet-4","name":"Anthropic: Claude Sonnet 4","size":"normal"},
    {"id":"anthropic/claude-sonnet-4.5","name":"Anthropic: Claude Sonnet 4.5","size":"normal"},
    {"id":"minimax/minimax-m1","name":"MiniMax: MiniMax M1","size":"normal"},
    {"id":"openai/gpt-5","name":"OpenAI: GPT-5","size":"normal"},
    {"id":"openai/gpt-5-codex","name":"OpenAI: GPT-5 Codex","size":"normal"},
    {"id":"openai/gpt-5-image","name":"OpenAI: GPT-5 Image","size":"normal"},
    {"id":"openai/gpt-5.1","name":"OpenAI: GPT-5.1","size":"normal"},
    {"id":"openai/gpt-5.1-codex","name":"OpenAI: GPT-5.1-Codex","size":"normal"},
    {"id":"openai/gpt-5.2","name":"OpenAI: GPT-5.2","size":"normal"},
    {"id":"openai/gpt-5.2-codex","name":"OpenAI: GPT-5.2-Codex","size":"normal"},
    {"id":"moonshotai/kimi-k2.5","name":"MoonshotAI: Kimi K2.5","size":"normal"},
    {"id":"qwen/qwen3-235b-a22b-thinking-2507","name":"Qwen: Qwen3 235B A22B Thinking 2507","size":"normal"},
    {"id":"qwen/qwen3-coder","name":"Qwen: Qwen3 Coder 480B A35B","size":"normal"},
    {"id":"qwen/qwen3-vl-235b-a22b-thinking","name":"Qwen: Qwen3 VL 235B A22B Thinking","size":"normal"},
    {"id":"qwen/qwen3-coder:exacto","name":"Qwen: Qwen3 Coder 480B A35B (exacto)","size":"normal"},
    {"id":"moonshotai/kimi-k2-thinking","name":"MoonshotAI: Kimi K2 Thinking","size":"normal"},
    {"id":"bytedance-seed/seed-1.6","name":"ByteDance Seed: Seed 1.6","size":"normal"},
    {"id":"bytedance-seed/seed-1.6-flash","name":"ByteDance Seed: Seed 1.6 Flash","size":"normal"},
    {"id":"qwen/qwen3-235b-a22b-2507","name":"Qwen: Qwen3 235B A22B Instruct 2507","size":"normal"},
    {"id":"xiaomi/mimo-v2-flash","name":"Xiaomi: MiMo-V2-Flash","size":"normal"},
    {"id":"qwen/qwen3-vl-8b-thinking","name":"Qwen: Qwen3 VL 8B Thinking","size":"normal"},
    {"id":"x-ai/grok-code-fast-1","name":"xAI: Grok Code Fast 1","size":"normal"},
    {"id":"x-ai/grok-4","name":"xAI: Grok 4","size":"normal"},
    {"id":"z-ai/glm-4.6:exacto","name":"Z.AI: GLM 4.6 (exacto)","size":"normal"},
    {"id":"z-ai/glm-4.6","name":"Z.AI: GLM 4.6","size":"normal"},
    {"id":"z-ai/glm-4.7","name":"Z.AI: GLM 4.7","size":"normal"},
    {"id":"z-ai/glm-4.7-flash","name":"Z.AI: GLM 4.7 Flash","size":"normal"},
    {"id":"openai/o3","name":"OpenAI: o3","size":"normal"},
    {"id":"openai/o3-deep-research","name":"OpenAI: o3 Deep Research","size":"normal"},
    {"id":"anthropic/claude-3.7-sonnet","name":"Anthropic: Claude 3.7 Sonnet","size":"normal"},
    {"id":"anthropic/claude-3.7-sonnet:thinking","name":"Anthropic: Claude 3.7 Sonnet (thinking)","size":"normal"},
    {"id":"anthropic/claude-haiku-4.5","name":"Anthropic: Claude Haiku 4.5","size":"normal"},
    {"id":"minimax/minimax-m2.1","name":"MiniMax: MiniMax M2.1","size":"normal"},
    {"id":"minimax/minimax-m2","name":"MiniMax: MiniMax M2","size":"normal"},
    {"id":"tngtech/deepseek-r1t2-chimera","name":"TNG: DeepSeek R1T2 Chimera","size":"normal"},
    {"id":"deepseek/deepseek-chat-v3-0324","name":"DeepSeek: DeepSeek V3 0324","size":"normal"},
    {"id":"deepseek/deepseek-r1-0528","name":"DeepSeek: R1 0528","size":"normal"},
    {"id":"deepseek/deepseek-v3.2","name":"DeepSeek: DeepSeek V3.2","size":"normal"},
    {"id":"deepseek/deepseek-v3.2-exp","name":"DeepSeek: DeepSeek V3.2 Exp","size":"normal"},
    {"id":"tngtech/tng-r1t-chimera","name":"TNG: R1T Chimera","size":"normal"},
    {"id":"tngtech/tng-r1t-chimera:free","name":"TNG: R1T Chimera (free)","size":"normal"},
    {"id":"deepseek/deepseek-v3.1-terminus","name":"DeepSeek: DeepSeek V3.1 Terminus","size":"normal"},
    {"id":"deepseek/deepseek-v3.1-terminus:exacto","name":"DeepSeek: DeepSeek V3.1 Terminus (exacto)","size":"normal"},
    {"id":"alibaba/tongyi-deepresearch-30b-a3b","name":"Tongyi DeepResearch 30B A3B","size":"normal"},
    {"id":"deepseek/deepseek-r1-distill-llama-70b","name":"DeepSeek: R1 Distill Llama 70B","size":"normal"},
    {"id":"nousresearch/hermes-4-70b","name":"Nous: Hermes 4 70B","size":"normal"},
    {"id":"openai/gpt-oss-20b","name":"OpenAI: gpt-oss-20b","size":"normal"},
    {"id":"prime-intellect/intellect-3","name":"Prime Intellect: INTELLECT-3","size":"normal"},
    {"id":"z-ai/glm-4.5-air","name":"Z.AI: GLM 4.5 Air","size":"normal"},
    {"id":"z-ai/glm-4.6v","name":"Z.AI: GLM 4.6V","size":"normal"},
    {"id":"z-ai/glm-4.5-air:free","name":"Z.AI: GLM 4.5 Air (free)","size":"normal"},
    {"id":"openai/gpt-oss-safeguard-20b","name":"OpenAI: gpt-oss-safeguard-20b","size":"normal"},
    {"id":"z-ai/glm-4.5","name":"Z.AI: GLM 4.5","size":"normal"},
    {"id":"qwen/qwen3-vl-30b-a3b-thinking","name":"Qwen: Qwen3 VL 30B A3B Thinking","size":"normal"},
    {"id":"nvidia/llama-3.3-nemotron-super-49b-v1.5","name":"NVIDIA: Llama 3.3 Nemotron Super 49B V1.5","size":"normal"},
    {"id":"openai/gpt-oss-120b","name":"OpenAI: gpt-oss-120b","size":"normal"},
    {"id":"openai/gpt-oss-120b:exacto","name":"OpenAI: gpt-oss-120b (exacto)","size":"normal"},
    {"id":"openai/gpt-oss-120b:free","name":"OpenAI: gpt-oss-120b (free)","size":"normal"},
    {"id":"openai/gpt-oss-20b:free","name":"OpenAI: gpt-oss-20b (free)","size":"normal"},
    {"id":"qwen/qwen3-next-80b-a3b-thinking","name":"Qwen: Qwen3 Next 80B A3B Thinking","size":"normal"},
    {"id":"stepfun-ai/step3","name":"StepFun: Step3","size":"normal"},
    {"id":"z-ai/glm-4.5v","name":"Z.AI: GLM 4.5V","size":"normal"},
    {"id":"deepseek/deepseek-r1","name":"DeepSeek: R1","size":"normal"},
    {"id":"qwen/qwen3-14b","name":"Qwen: Qwen3 14B","size":"normal"},
    {"id":"qwen/qwen3-30b-a3b","name":"Qwen: Qwen3 30B A3B","size":"normal"},
    {"id":"qwen/qwen3-32b","name":"Qwen: Qwen3 32B","size":"normal"},
    {"id":"qwen/qwen3-235b-a22b","name":"Qwen: Qwen3 235B A22B","size":"normal"},
    {"id":"qwen/qwen3-4b:free","name":"Qwen: Qwen3 4B (free)","size":"normal"},
    {"id":"nousresearch/deephermes-3-mistral-24b-preview","name":"Nous: DeepHermes 3 Mistral 24B Preview","size":"normal"},
    {"id":"deepseek/deepseek-chat-v3.1","name":"DeepSeek: DeepSeek V3.1","size":"normal"},
    {"id":"deepcogito/cogito-v2-preview-llama-405b","name":"Deep Cogito: Cogito V2 Preview Llama 405B","size":"normal"},
    {"id":"deepcogito/cogito-v2-preview-llama-70b","name":"Deep Cogito: Cogito V2 Preview Llama 70B","size":"normal"},
    {"id":"qwen/qwen3-30b-a3b-thinking-2507","name":"Qwen: Qwen3 30B A3B Thinking 2507","size":"normal"},
    {"id":"qwen/qwq-32b","name":"Qwen: QwQ 32B","size":"normal"},
    {"id":"deepcogito/cogito-v2-preview-llama-109b-moe","name":"Cogito V2 Preview Llama 109B","size":"normal"},
    {"id":"qwen/qwen3-8b","name":"Qwen: Qwen3 8B","size":"normal"},
    {"id":"baidu/ernie-4.5-vl-28b-a3b","name":"Baidu: ERNIE 4.5 VL 28B A3B","size":"normal"},
    {"id":"google/gemini-2.5-flash-preview-09-2025","name":"Google: Gemini 2.5 Flash Preview 09-2025","size":"small"},
    {"id":"google/gemini-2.5-flash","name":"Google: Gemini 2.5 Flash","size":"small"},
    {"id":"google/gemini-2.5-flash-lite","name":"Google: Gemini 2.5 Flash Lite","size":"small"},
    {"id":"google/gemini-2.5-flash-lite-preview-09-2025","name":"Google: Gemini 2.5 Flash Lite Preview 09-2025","size":"small"},
    {"id":"google/gemini-3-flash-preview","name":"Google: Gemini 3 Flash Preview","size":"small"},
    {"id":"amazon/nova-2-lite-v1","name":"Amazon: Nova 2 Lite","size":"normal"},
    {"id":"openai/gpt-5-image-mini","name":"OpenAI: GPT-5 Image Mini","size":"normal"},
    {"id":"openai/gpt-5-mini","name":"OpenAI: GPT-5 Mini","size":"normal"},
    {"id":"openai/gpt-5-nano","name":"OpenAI: GPT-5 Nano","size":"normal"},
    {"id":"openai/gpt-5.1-codex-mini","name":"OpenAI: GPT-5.1-Codex-Mini","size":"normal"},
    {"id":"nvidia/nemotron-3-nano-30b-a3b","name":"NVIDIA: Nemotron 3 Nano 30B A3B","size":"normal"},
    {"id":"nvidia/nemotron-3-nano-30b-a3b:free","name":"NVIDIA: Nemotron 3 Nano 30B A3B (free)","size":"normal"},
    {"id":"openai/o4-mini","name":"OpenAI: o4 Mini","size":"normal"},
    {"id":"openai/o4-mini-deep-research","name":"OpenAI: o4 Mini Deep Research","size":"normal"},
    {"id":"openai/o4-mini-high","name":"OpenAI: o4 Mini High","size":"normal"},
    {"id":"arcee-ai/trinity-mini","name":"Arcee AI: Trinity Mini","size":"normal"},
    {"id":"arcee-ai/trinity-mini:free","name":"Arcee AI: Trinity Mini (free)","size":"normal"},
    {"id":"nvidia/nemotron-nano-9b-v2","name":"NVIDIA: Nemotron Nano 9B V2","size":"normal"},
    {"id":"x-ai/grok-3-mini","name":"xAI: Grok 3 Mini","size":"normal"},
    {"id":"x-ai/grok-3-mini-beta","name":"xAI: Grok 3 Mini Beta","size":"normal"},
    {"id":"nvidia/nemotron-nano-12b-v2-vl:free","name":"NVIDIA: Nemotron Nano 12B 2 VL (free)","size":"normal"},
    {"id":"nvidia/nemotron-nano-9b-v2:free","name":"NVIDIA: Nemotron Nano 9B V2 (free)","size":"normal"},
    {"id":"amazon/nova-pro-v1","name":"Amazon: Nova Pro 1.0","size":"normal"},
    {"id":"kwaipilot/kat-coder-pro","name":"Kwaipilot: KAT-Coder-Pro V1","size":"normal"},
    {"id":"qwen/qwen3-max","name":"Qwen: Qwen3 Max","size":"normal"},
    {"id":"qwen/qwen-plus","name":"Qwen: Qwen-Plus","size":"normal"},
    {"id":"qwen/qwen-vl-max","name":"Qwen: Qwen VL Max","size":"normal"},
    {"id":"qwen/qwen3-coder-plus","name":"Qwen: Qwen3 Coder Plus","size":"normal"},
    {"id":"cohere/command-r-plus-08-2024","name":"Cohere: Command R+ (08-2024)","size":"normal"},
    {"id":"qwen/qwen-max","name":"Qwen: Qwen-Max ","size":"normal"},
    {"id":"mistralai/devstral-medium","name":"Mistral: Devstral Medium","size":"normal"},
    {"id":"mistralai/mistral-medium-3","name":"Mistral: Mistral Medium 3","size":"normal"},
    {"id":"mistralai/mistral-medium-3.1","name":"Mistral: Mistral Medium 3.1","size":"normal"},
    {"id":"meta-llama/llama-4-maverick","name":"Meta: Llama 4 Maverick","size":"normal"},
    {"id":"openai/gpt-4.1","name":"OpenAI: GPT-4.1","size":"normal"},
    {"id":"amazon/nova-premier-v1","name":"Amazon: Nova Premier 1.0","size":"normal"},
    {"id":"qwen/qwen-turbo","name":"Qwen: Qwen-Turbo","size":"normal"},
    {"id":"meta-llama/llama-4-scout","name":"Meta: Llama 4 Scout","size":"normal"},
    {"id":"moonshotai/kimi-k2-0905","name":"MoonshotAI: Kimi K2 0905","size":"normal"},
    {"id":"qwen/qwen3-30b-a3b-instruct-2507","name":"Qwen: Qwen3 30B A3B Instruct 2507","size":"normal"},
    {"id":"mistralai/devstral-2512","name":"Mistral: Devstral 2 2512","size":"normal"},
    {"id":"mistralai/mistral-large-2512","name":"Mistral: Mistral Large 3 2512","size":"normal"},
    {"id":"moonshotai/kimi-k2-0905:exacto","name":"MoonshotAI: Kimi K2 0905 (exacto)","size":"normal"},
    {"id":"qwen/qwen3-next-80b-a3b-instruct","name":"Qwen: Qwen3 Next 80B A3B Instruct","size":"normal"},
    {"id":"qwen/qwen3-next-80b-a3b-instruct:free","name":"Qwen: Qwen3 Next 80B A3B Instruct (free)","size":"normal"},
    {"id":"qwen/qwen3-vl-235b-a22b-instruct","name":"Qwen: Qwen3 VL 235B A22B Instruct","size":"normal"},
    {"id":"qwen/qwen3-vl-30b-a3b-instruct","name":"Qwen: Qwen3 VL 30B A3B Instruct","size":"normal"},
    {"id":"qwen/qwen3-coder:free","name":"Qwen: Qwen3 Coder 480B A35B (free)","size":"normal"},
    {"id":"relace/relace-search","name":"Relace: Relace Search","size":"normal"},
    {"id":"ai21/jamba-large-1.7","name":"AI21: Jamba Large 1.7","size":"normal"},
    {"id":"mistralai/codestral-2508","name":"Mistral: Codestral 2508","size":"normal"},
    {"id":"openai/o1","name":"OpenAI: o1","size":"normal"},
    {"id":"anthropic/claude-3.5-haiku","name":"Anthropic: Claude 3.5 Haiku","size":"normal"},
    {"id":"anthropic/claude-3.5-sonnet","name":"Anthropic: Claude 3.5 Sonnet","size":"normal"},
    {"id":"anthropic/claude-3-haiku","name":"Anthropic: Claude 3 Haiku","size":"normal"},
    {"id":"deepseek/deepseek-chat","name":"DeepSeek: DeepSeek V3","size":"normal"},
    {"id":"qwen/qwen3-coder-30b-a3b-instruct","name":"Qwen: Qwen3 Coder 30B A3B Instruct","size":"normal"},
    {"id":"nex-agi/deepseek-v3.1-nex-n1","name":"Nex AGI: DeepSeek V3.1 Nex N1","size":"normal"},
    {"id":"arcee-ai/virtuoso-large","name":"Arcee AI: Virtuoso Large","size":"normal"},
    {"id":"qwen/qwen3-vl-8b-instruct","name":"Qwen: Qwen3 VL 8B Instruct","size":"normal"},
    {"id":"meta-llama/llama-3.3-70b-instruct","name":"Meta: Llama 3.3 70B Instruct","size":"normal"},
    {"id":"mistralai/mistral-nemo","name":"Mistral: Mistral Nemo","size":"normal"},
    {"id":"nvidia/llama-3.1-nemotron-70b-instruct","name":"NVIDIA: Llama 3.1 Nemotron 70B Instruct","size":"normal"},
    {"id":"google/gemma-3-27b-it:free","name":"Google: Gemma 3 27B (free)","size":"normal"},
    {"id":"meta-llama/llama-3.1-70b-instruct","name":"Meta: Llama 3.1 70B Instruct","size":"normal"},
    {"id":"meta-llama/llama-3.3-70b-instruct:free","name":"Meta: Llama 3.3 70B Instruct (free)","size":"normal"},
    {"id":"mistralai/mistral-large-2407","name":"Mistral Large 2407","size":"normal"},
    {"id":"mistralai/mistral-large-2411","name":"Mistral Large 2411","size":"normal"},
    {"id":"mistralai/pixtral-large-2411","name":"Mistral: Pixtral Large 2411","size":"normal"},
    {"id":"moonshotai/kimi-k2","name":"MoonshotAI: Kimi K2 0711","size":"normal"},
    {"id":"x-ai/grok-3","name":"xAI: Grok 3","size":"normal"},
    {"id":"x-ai/grok-3-beta","name":"xAI: Grok 3 Beta","size":"normal"},
    {"id":"arcee-ai/trinity-large-preview:free","name":"Arcee AI: Trinity Large Preview (free)","size":"normal"},
    {"id":"qwen/qwen3-coder-flash","name":"Qwen: Qwen3 Coder Flash","size":"normal"},
    {"id":"openai/gpt-4o:extended","name":"OpenAI: GPT-4o (extended)","size":"normal"},
    {"id":"inception/mercury","name":"Inception: Mercury","size":"normal"},
    {"id":"inception/mercury-coder","name":"Inception: Mercury Coder","size":"normal"},
    {"id":"openai/gpt-4o","name":"OpenAI: GPT-4o","size":"normal"},
    {"id":"openai/gpt-4o-audio-preview","name":"OpenAI: GPT-4o Audio","size":"normal"},
    {"id":"openai/gpt-5.1-chat","name":"OpenAI: GPT-5.1 Chat","size":"normal"},
    {"id":"openai/gpt-5.2-chat","name":"OpenAI: GPT-5.2 Chat","size":"normal"},
    {"id":"amazon/nova-micro-v1","name":"Amazon: Nova Micro 1.0","size":"normal"},
    {"id":"mistralai/mistral-large","name":"Mistral Large","size":"normal"},
    {"id":"openai/gpt-4-1106-preview","name":"OpenAI: GPT-4 Turbo (older v1106)","size":"normal"},
    {"id":"openai/gpt-4-turbo","name":"OpenAI: GPT-4 Turbo","size":"normal"},
    {"id":"openai/gpt-4-turbo-preview","name":"OpenAI: GPT-4 Turbo Preview","size":"normal"},
    {"id":"z-ai/glm-4-32b","name":"Z.AI: GLM 4 32B ","size":"normal"},
    {"id":"cohere/command-r-08-2024","name":"Cohere: Command R (08-2024)","size":"normal"},
    {"id":"baidu/ernie-4.5-21b-a3b","name":"Baidu: ERNIE 4.5 21B A3B","size":"normal"},
    {"id":"google/gemma-3-27b-it","name":"Google: Gemma 3 27B","size":"normal"},
    {"id":"allenai/olmo-3.1-32b-instruct","name":"AllenAI: Olmo 3.1 32B Instruct","size":"normal"},
    {"id":"mistralai/mixtral-8x22b-instruct","name":"Mistral: Mixtral 8x22B Instruct","size":"normal"},
    {"id":"mistralai/mixtral-8x7b-instruct","name":"Mistral: Mixtral 8x7B Instruct","size":"normal"},
    {"id":"qwen/qwen-2.5-72b-instruct","name":"Qwen2.5 72B Instruct","size":"normal"},
    {"id":"mistralai/mistral-saba","name":"Mistral: Saba","size":"normal"},
    {"id":"mistralai/pixtral-12b","name":"Mistral: Pixtral 12B","size":"normal"},
    {"id":"qwen/qwen-2.5-7b-instruct","name":"Qwen: Qwen2.5 7B Instruct","size":"normal"},
    {"id":"sao10k/l3.1-euryale-70b","name":"Sao10K: Llama 3.1 Euryale 70B v2.2","size":"normal"},
    {"id":"thedrummer/rocinante-12b","name":"TheDrummer: Rocinante 12B","size":"normal"},
    {"id":"thedrummer/unslopnemo-12b","name":"TheDrummer: UnslopNemo 12B","size":"normal"},
    {"id":"openai/gpt-3.5-turbo","name":"OpenAI: GPT-3.5 Turbo","size":"normal"},
    {"id":"openai/gpt-3.5-turbo-16k","name":"OpenAI: GPT-3.5 Turbo 16k","size":"normal"},
    {"id":"meta-llama/llama-3.1-8b-instruct","name":"Meta: Llama 3.1 8B Instruct","size":"normal"},
    {"id":"meta-llama/llama-3.1-405b-instruct","name":"Meta: Llama 3.1 405B Instruct","size":"normal"},
    {"id":"meta-llama/llama-3-8b-instruct","name":"Meta: Llama 3 8B Instruct","size":"normal"},
    {"id":"sao10k/l3-euryale-70b","name":"Sao10k: Llama 3 Euryale 70B v2.1","size":"normal"},
    {"id":"openai/gpt-4","name":"OpenAI: GPT-4","size":"normal"},
    {"id":"openai/gpt-4-0314","name":"OpenAI: GPT-4 (older v0314)","size":"normal"},
    {"id":"openai/gpt-3.5-turbo-0613","name":"OpenAI: GPT-3.5 Turbo (older v0613)","size":"normal"},
    {"id":"google/gemini-2.0-flash-001","name":"Google: Gemini 2.0 Flash","size":"small"},
    {"id":"google/gemini-2.0-flash-exp:free","name":"Google: Gemini 2.0 Flash Experimental (free)","size":"small"},
    {"id":"google/gemini-2.0-flash-lite-001","name":"Google: Gemini 2.0 Flash Lite","size":"small"},
    {"id":"openai/gpt-4.1-mini","name":"OpenAI: GPT-4.1 Mini","size":"normal"},
    {"id":"openai/gpt-4.1-nano","name":"OpenAI: GPT-4.1 Nano","size":"normal"},
    {"id":"amazon/nova-lite-v1","name":"Amazon: Nova Lite 1.0","size":"normal"},
    {"id":"mistralai/ministral-14b-2512","name":"Mistral: Ministral 3 14B 2512","size":"normal"},
    {"id":"mistralai/ministral-8b-2512","name":"Mistral: Ministral 3 8B 2512","size":"normal"},
    {"id":"ai21/jamba-mini-1.7","name":"AI21: Jamba Mini 1.7","size":"normal"},
    {"id":"openai/o3-mini","name":"OpenAI: o3 Mini","size":"normal"},
    {"id":"openai/o3-mini-high","name":"OpenAI: o3 Mini High","size":"normal"},
    {"id":"mistralai/mistral-small-3.1-24b-instruct","name":"Mistral: Mistral Small 3.1 24B","size":"normal"},
    {"id":"mistralai/mistral-small-3.2-24b-instruct","name":"Mistral: Mistral Small 3.2 24B","size":"normal"},
    {"id":"mistralai/devstral-small","name":"Mistral: Devstral Small 1.1","size":"normal"},
    {"id":"mistralai/ministral-3b","name":"Mistral: Ministral 3B","size":"normal"},
    {"id":"mistralai/ministral-3b-2512","name":"Mistral: Ministral 3 3B 2512","size":"normal"},
    {"id":"mistralai/ministral-8b","name":"Mistral: Ministral 8B","size":"normal"},
    {"id":"openai/gpt-4o-mini","name":"OpenAI: GPT-4o-mini","size":"normal"},
    {"id":"mistralai/mistral-small-3.1-24b-instruct:free","name":"Mistral: Mistral Small 3.1 24B (free)","size":"normal"},
    {"id":"mistralai/mistral-small-24b-instruct-2501","name":"Mistral: Mistral Small 3","size":"normal"},
    {"id":"mistralai/mistral-small-creative","name":"Mistral: Mistral Small Creative","size":"normal"},
    {"id":"mistralai/mistral-tiny","name":"Mistral Tiny","size":"normal"},
    {"id":"mistralai/voxtral-small-24b-2507","name":"Mistral: Voxtral Small 24B 2507","size":"normal"},
  ],
  "vercel-ai-gateway": [
    {"id":"anthropic/claude-3.5-sonnet-20240620","name":"Claude 3.5 Sonnet (2024-06-20)","size":"normal"},
    {"id":"openai/gpt-5-pro","name":"GPT-5 pro","size":"normal"},
    {"id":"openai/gpt-5.1-codex-max","name":"GPT 5.1 Codex Max","size":"normal"},
    {"id":"openai/gpt-5.2-pro","name":"GPT 5.2 ","size":"normal"},
    {"id":"alibaba/qwen3-max-thinking","name":"Qwen 3 Max Thinking","size":"normal"},
    {"id":"openai/o3-pro","name":"o3 Pro","size":"normal"},
    {"id":"anthropic/claude-opus-4.5","name":"Claude Opus 4.5","size":"large"},
    {"id":"anthropic/claude-opus-4","name":"Claude Opus 4","size":"large"},
    {"id":"anthropic/claude-opus-4.1","name":"Claude Opus 4.1","size":"large"},
    {"id":"xai/grok-4-fast-reasoning","name":"Grok 4 Fast Reasoning","size":"normal"},
    {"id":"xai/grok-4.1-fast-reasoning","name":"Grok 4.1 Fast Reasoning","size":"normal"},
    {"id":"google/gemini-2.5-pro","name":"Gemini 2.5 Pro","size":"normal"},
    {"id":"anthropic/claude-sonnet-4","name":"Claude Sonnet 4","size":"normal"},
    {"id":"anthropic/claude-sonnet-4.5","name":"Claude Sonnet 4.5","size":"normal"},
    {"id":"google/gemini-3-pro-preview","name":"Gemini 3 Pro Preview","size":"normal"},
    {"id":"openai/gpt-5","name":"GPT-5","size":"normal"},
    {"id":"openai/gpt-5-codex","name":"GPT-5-Codex","size":"normal"},
    {"id":"openai/gpt-5.1-codex","name":"GPT-5.1-Codex","size":"normal"},
    {"id":"openai/gpt-5.1-thinking","name":"GPT 5.1 Thinking","size":"normal"},
    {"id":"openai/gpt-5.2","name":"GPT-5.2","size":"normal"},
    {"id":"openai/gpt-5.2-codex","name":"GPT-5.2-Codex","size":"normal"},
    {"id":"xiaomi/mimo-v2-flash","name":"MiMo V2 Flash","size":"normal"},
    {"id":"alibaba/qwen3-235b-a22b-thinking","name":"Qwen3 235B A22B Thinking 2507","size":"normal"},
    {"id":"minimax/minimax-m2","name":"MiniMax M2","size":"normal"},
    {"id":"moonshotai/kimi-k2-thinking-turbo","name":"Kimi K2 Thinking Turbo","size":"normal"},
    {"id":"moonshotai/kimi-k2.5","name":"Kimi K2.5","size":"normal"},
    {"id":"xai/grok-4","name":"Grok 4","size":"normal"},
    {"id":"xai/grok-code-fast-1","name":"Grok Code Fast 1","size":"normal"},
    {"id":"bytedance/seed-1.6","name":"Seed 1.6","size":"normal"},
    {"id":"moonshotai/kimi-k2-thinking","name":"Kimi K2 Thinking","size":"normal"},
    {"id":"minimax/minimax-m2.1-lightning","name":"MiniMax M2.1 Lightning","size":"normal"},
    {"id":"zai/glm-4.7","name":"GLM 4.7","size":"normal"},
    {"id":"zai/glm-4.7-flashx","name":"GLM 4.7 FlashX","size":"normal"},
    {"id":"openai/o1","name":"o1","size":"normal"},
    {"id":"openai/o3","name":"o3","size":"normal"},
    {"id":"openai/o3-deep-research","name":"o3-deep-research","size":"normal"},
    {"id":"zai/glm-4.6","name":"GLM 4.6","size":"normal"},
    {"id":"anthropic/claude-3.7-sonnet","name":"Claude 3.7 Sonnet","size":"normal"},
    {"id":"anthropic/claude-haiku-4.5","name":"Claude Haiku 4.5","size":"normal"},
    {"id":"minimax/minimax-m2.1","name":"MiniMax M2.1","size":"normal"},
    {"id":"deepseek/deepseek-v3.2-exp","name":"DeepSeek V3.2 Exp","size":"normal"},
    {"id":"deepseek/deepseek-v3.1","name":"DeepSeek-V3.1","size":"normal"},
    {"id":"alibaba/qwen3-coder-30b-a3b","name":"Qwen 3 Coder 30B A3B Instruct","size":"normal"},
    {"id":"openai/gpt-oss-120b","name":"gpt-oss-120b","size":"normal"},
    {"id":"prime-intellect/intellect-3","name":"INTELLECT 3","size":"normal"},
    {"id":"zai/glm-4.5","name":"GLM-4.5","size":"normal"},
    {"id":"deepseek/deepseek-v3.1-terminus","name":"DeepSeek V3.1 Terminus","size":"normal"},
    {"id":"openai/gpt-oss-safeguard-20b","name":"gpt-oss-safeguard-20b","size":"normal"},
    {"id":"zai/glm-4.5-air","name":"GLM 4.5 Air","size":"normal"},
    {"id":"deepseek/deepseek-v3.2-thinking","name":"DeepSeek V3.2 Thinking","size":"normal"},
    {"id":"zai/glm-4.6v","name":"GLM-4.6V","size":"normal"},
    {"id":"zai/glm-4.6v-flash","name":"GLM-4.6V-Flash","size":"normal"},
    {"id":"openai/gpt-5-chat","name":"GPT-5 Chat","size":"normal"},
    {"id":"openai/gpt-5.1-instant","name":"GPT-5.1 Instant","size":"normal"},
    {"id":"openai/gpt-5.2-chat","name":"GPT-5.2 Chat","size":"normal"},
    {"id":"meituan/longcat-flash-thinking","name":"LongCat Flash Thinking","size":"normal"},
    {"id":"openai/gpt-oss-20b","name":"gpt-oss-20b","size":"normal"},
    {"id":"zai/glm-4.5v","name":"GLM 4.5V","size":"normal"},
    {"id":"alibaba/qwen-3-14b","name":"Qwen3-14B","size":"normal"},
    {"id":"alibaba/qwen-3-30b","name":"Qwen3-30B-A3B","size":"normal"},
    {"id":"alibaba/qwen-3-32b","name":"Qwen 3.32B","size":"normal"},
    {"id":"google/gemini-2.5-flash-lite","name":"Gemini 2.5 Flash Lite","size":"small"},
    {"id":"google/gemini-2.5-flash-lite-preview-09-2025","name":"Gemini 2.5 Flash Lite Preview 09-2025","size":"small"},
    {"id":"google/gemini-2.5-flash","name":"Gemini 2.5 Flash","size":"small"},
    {"id":"google/gemini-2.5-flash-preview-09-2025","name":"Gemini 2.5 Flash Preview 09-2025","size":"small"},
    {"id":"google/gemini-3-flash","name":"Gemini 3 Flash","size":"small"},
    {"id":"openai/gpt-5-mini","name":"GPT-5 mini","size":"normal"},
    {"id":"openai/gpt-5-nano","name":"GPT-5 nano","size":"normal"},
    {"id":"openai/gpt-5.1-codex-mini","name":"GPT-5.1 Codex mini","size":"normal"},
    {"id":"openai/codex-mini","name":"Codex Mini","size":"normal"},
    {"id":"openai/o3-mini","name":"o3-mini","size":"normal"},
    {"id":"openai/o4-mini","name":"o4-mini","size":"normal"},
    {"id":"nvidia/nemotron-nano-12b-v2-vl","name":"Nvidia Nemotron Nano 12B V2 VL","size":"normal"},
    {"id":"nvidia/nemotron-nano-9b-v2","name":"Nvidia Nemotron Nano 9B V2","size":"normal"},
    {"id":"alibaba/qwen3-coder-plus","name":"Qwen3 Coder Plus","size":"normal"},
    {"id":"alibaba/qwen3-max","name":"Qwen3 Max","size":"normal"},
    {"id":"alibaba/qwen3-max-preview","name":"Qwen3 Max Preview","size":"normal"},
    {"id":"perplexity/sonar-pro","name":"Sonar Pro","size":"normal"},
    {"id":"mistral/mistral-medium","name":"Mistral Medium 3.1","size":"normal"},
    {"id":"xai/grok-4-fast-non-reasoning","name":"Grok 4 Fast Non-Reasoning","size":"normal"},
    {"id":"stealth/sonoma-dusk-alpha","name":"Sonoma Dusk Alpha","size":"normal"},
    {"id":"stealth/sonoma-sky-alpha","name":"Sonoma Sky Alpha","size":"normal"},
    {"id":"xai/grok-4.1-fast-non-reasoning","name":"Grok 4.1 Fast Non-Reasoning","size":"normal"},
    {"id":"openai/gpt-4.1","name":"GPT-4.1","size":"normal"},
    {"id":"alibaba/qwen3-coder","name":"Qwen3 Coder 480B A35B Instruct","size":"normal"},
    {"id":"mistral/devstral-2","name":"Devstral 2","size":"normal"},
    {"id":"moonshotai/kimi-k2-turbo","name":"Kimi K2 Turbo","size":"normal"},
    {"id":"cohere/command-a","name":"Command A","size":"normal"},
    {"id":"anthropic/claude-3.5-haiku","name":"Claude 3.5 Haiku","size":"normal"},
    {"id":"anthropic/claude-3.5-sonnet","name":"Claude 3.5 Sonnet","size":"normal"},
    {"id":"anthropic/claude-3-haiku","name":"Claude 3 Haiku","size":"normal"},
    {"id":"deepseek/deepseek-v3","name":"DeepSeek V3 0324","size":"normal"},
    {"id":"xai/grok-3","name":"Grok 3 Beta","size":"normal"},
    {"id":"xai/grok-3-fast","name":"Grok 3 Fast Beta","size":"normal"},
    {"id":"meta/llama-3.1-70b","name":"Llama 3.1 70B Instruct","size":"normal"},
    {"id":"meta/llama-3.1-8b","name":"Llama 3.1 8B Instruct","size":"normal"},
    {"id":"moonshotai/kimi-k2","name":"Kimi K2","size":"normal"},
    {"id":"meta/llama-4-maverick","name":"Llama 4 Maverick 17B Instruct","size":"normal"},
    {"id":"meta/llama-4-scout","name":"Llama 4 Scout 17B Instruct","size":"normal"},
    {"id":"arcee-ai/trinity-large-preview","name":"Trinity Large Preview","size":"normal"},
    {"id":"vercel/v0-1.5-md","name":"v0-1.5-md","size":"normal"},
    {"id":"vercel/v0-1.0-md","name":"v0-1.0-md","size":"normal"},
    {"id":"openai/gpt-4o","name":"GPT-4o","size":"normal"},
    {"id":"meituan/longcat-flash-chat","name":"LongCat Flash Chat","size":"normal"},
    {"id":"meta/llama-3.2-11b","name":"Llama 3.2 11B Vision Instruct","size":"normal"},
    {"id":"meta/llama-3.2-90b","name":"Llama 3.2 90B Vision Instruct","size":"normal"},
    {"id":"meta/llama-3.3-70b","name":"Llama 3.3 70B Instruct","size":"normal"},
    {"id":"openai/gpt-4-turbo","name":"GPT-4 Turbo","size":"normal"},
    {"id":"mistral/codestral","name":"Mistral Codestral","size":"normal"},
    {"id":"mistral/pixtral-12b","name":"Pixtral 12B 2409","size":"normal"},
    {"id":"mistral/pixtral-large","name":"Pixtral Large","size":"normal"},
    {"id":"perplexity/sonar","name":"Sonar","size":"normal"},
    {"id":"alibaba/qwen-3-235b","name":"Qwen3 235B A22b Instruct 2507","size":"normal"},
    {"id":"xai/grok-2-vision","name":"Grok 2 Vision","size":"normal"},
    {"id":"openai/gpt-4.1-mini","name":"GPT-4.1 mini","size":"normal"},
    {"id":"openai/gpt-4.1-nano","name":"GPT-4.1 nano","size":"normal"},
    {"id":"mistral/devstral-small-2","name":"Devstral Small 2","size":"normal"},
    {"id":"xai/grok-3-mini","name":"Grok 3 Mini Beta","size":"normal"},
    {"id":"xai/grok-3-mini-fast","name":"Grok 3 Mini Fast Beta","size":"normal"},
    {"id":"mistral/devstral-small","name":"Devstral Small 1.1","size":"normal"},
    {"id":"openai/gpt-4o-mini","name":"GPT-4o mini","size":"normal"},
    {"id":"mistral/ministral-3b","name":"Ministral 3B","size":"normal"},
    {"id":"mistral/ministral-8b","name":"Ministral 8B","size":"normal"},
    {"id":"inception/mercury-coder-small","name":"Mercury Coder Small Beta","size":"normal"},
    {"id":"mistral/mistral-small","name":"Mistral Small","size":"normal"},
  ],
  "xai": [
    {"id":"grok-3-mini-fast-latest","name":"Grok 3 Mini Fast Latest","size":"normal"},
    {"id":"grok-3-mini-latest","name":"Grok 3 Mini Latest","size":"normal"},
    {"id":"grok-2-latest","name":"Grok 2 Latest","size":"normal"},
    {"id":"grok-3-fast-latest","name":"Grok 3 Fast Latest","size":"normal"},
    {"id":"grok-3-latest","name":"Grok 3 Latest","size":"normal"},
    {"id":"grok-2-vision-latest","name":"Grok 2 Vision Latest","size":"normal"},
    {"id":"grok-4-1-fast","name":"Grok 4.1 Fast","size":"normal"},
    {"id":"grok-4-fast","name":"Grok 4 Fast","size":"normal"},
    {"id":"grok-4","name":"Grok 4","size":"normal"},
    {"id":"grok-code-fast-1","name":"Grok Code Fast 1","size":"normal"},
    {"id":"grok-3-mini","name":"Grok 3 Mini","size":"normal"},
    {"id":"grok-3-mini-fast","name":"Grok 3 Mini Fast","size":"normal"},
    {"id":"grok-4-1-fast-non-reasoning","name":"Grok 4.1 Fast (Non-Reasoning)","size":"normal"},
    {"id":"grok-4-fast-non-reasoning","name":"Grok 4 Fast (Non-Reasoning)","size":"normal"},
    {"id":"grok-2","name":"Grok 2","size":"normal"},
    {"id":"grok-2-1212","name":"Grok 2 (1212)","size":"normal"},
    {"id":"grok-3","name":"Grok 3","size":"normal"},
    {"id":"grok-3-fast","name":"Grok 3 Fast","size":"normal"},
    {"id":"grok-beta","name":"Grok Beta","size":"normal"},
    {"id":"grok-2-vision","name":"Grok 2 Vision","size":"normal"},
    {"id":"grok-2-vision-1212","name":"Grok 2 Vision (1212)","size":"normal"},
    {"id":"grok-vision-beta","name":"Grok Vision Beta","size":"normal"},
  ],
  "zai": [
    {"id":"glm-4.6","name":"GLM-4.6","size":"normal"},
    {"id":"glm-4.7","name":"GLM-4.7","size":"normal"},
    {"id":"glm-4.7-flash","name":"GLM-4.7-Flash","size":"normal"},
    {"id":"glm-4.5","name":"GLM-4.5","size":"normal"},
    {"id":"glm-4.5-air","name":"GLM-4.5-Air","size":"normal"},
    {"id":"glm-4.5-flash","name":"GLM-4.5-Flash","size":"normal"},
    {"id":"glm-4.6v","name":"GLM-4.6V","size":"normal"},
    {"id":"glm-4.5v","name":"GLM-4.5V","size":"normal"},
  ],
} as const satisfies ProviderModelRegistry;

type ProviderModelKeys = keyof typeof PROVIDER_MODELS;
type ExtraProviderKeys = Exclude<ProviderModelKeys, KnownProvider>;
const _assertNoExtraProviders: ExtraProviderKeys extends never ? true : never = true;
void _assertNoExtraProviders;

const SIZE_ORDER: Record<ProviderModelInfo["size"], number> = {
  large: 3,
  normal: 2,
  small: 1,
  unknown: 0
};

export function listProviderModels(providerId: string): ProviderModelInfo[] {
  const models =
    (PROVIDER_MODELS as Record<string, ProviderModelInfo[]>)[providerId] ?? [];
  return [...models].sort(compareProviderModels);
}

function compareProviderModels(a: ProviderModelInfo, b: ProviderModelInfo): number {
  const scoreA = parseModelScore(a);
  const scoreB = parseModelScore(b);

  if (scoreA.latest !== scoreB.latest) {
    return scoreA.latest ? -1 : 1;
  }
  if (scoreA.version !== scoreB.version) {
    return scoreB.version - scoreA.version;
  }
  if (scoreA.date !== scoreB.date) {
    return scoreB.date - scoreA.date;
  }

  const sizeDelta = (SIZE_ORDER[b.size] ?? 0) - (SIZE_ORDER[a.size] ?? 0);
  if (sizeDelta !== 0) {
    return sizeDelta;
  }

  return a.name.localeCompare(b.name);
}

function parseModelScore(model: ProviderModelInfo): {
  latest: boolean;
  version: number;
  date: number;
} {
  const value = `${model.id} ${model.name}`.toLowerCase();
  return {
    latest: value.includes("latest"),
    version: parseVersionScore(value),
    date: parseDateScore(value)
  };
}

function parseDateScore(value: string): number {
  const match = value.match(/(20\d{2})[-_/]?(\d{2})(?:[-_/]?(\d{2}))?/);
  if (!match) {
    return 0;
  }
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3] ?? "01");
  if (!year || !month) {
    return 0;
  }
  return year * 10000 + month * 100 + day;
}

function parseVersionScore(value: string): number {
  const cleaned = value.replace(/20\d{2}[-_/]?\d{2}(?:[-_/]?\d{2})?/g, " ");
  const versionMatch = cleaned.match(/(\d{1,2})(?:[.-](\d{1,2}))(?:[.-](\d{1,2}))?/);
  if (versionMatch) {
    const major = Number(versionMatch[1]);
    const minor = Number(versionMatch[2] ?? "0");
    const patch = Number(versionMatch[3] ?? "0");
    if (Number.isFinite(major) && Number.isFinite(minor) && Number.isFinite(patch)) {
      return major * 10000 + minor * 100 + patch;
    }
  }

  const major = findMajorVersion(cleaned);
  if (major > 0) {
    return major * 10000;
  }
  return 0;
}

function findMajorVersion(value: string): number {
  const matcher = /\d{1,2}/g;
  let match: RegExpExecArray | null;
  while ((match = matcher.exec(value))) {
    const index = match.index ?? 0;
    const end = index + match[0].length;
    const prev = value[index - 1] ?? "";
    const next = value[end] ?? "";

    if (prev && /\d/.test(prev)) {
      continue;
    }
    if (next.toLowerCase() === "b") {
      continue;
    }

    const parsed = Number(match[0]);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }
  return 0;
}
